### ISSUE TITLE
Errors building on Ubuntu 17.10

### ISSUE THREAD

**Issue by thibaudk** [bltzr/ofxOscQuery#1]
the errors concern the building of 
https://github.com/bltzr/ofxOscQuery/tree/master/example-singleServer

first type of errors:
In file included from /home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOssiaNode.h:4:0,
                 from /home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOscQueryServer.h:9,
                 from /home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOscQueryServer.cpp:9:
/home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOssiaTypes.h:213:22: error: ‘string’ does not name a type; did you mean ‘stdin’?
     using ofx_type = string;
                      ^~~~~~
                      stdin

second type of error:
/usr/include/c++/7/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = ofxOssiaNode; _Args = {opp::oscquery_server&, ofParameterGroup&}; _Tp = std::_List_node<ofxOssiaNode>]’:
/usr/include/c++/7/bits/alloc_traits.h:475:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = ofxOssiaNode; _Args = {opp::oscquery_server&, ofParameterGroup&}; _Tp = std::_List_node<ofxOssiaNode>; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::_List_node<ofxOssiaNode> >]’
/usr/include/c++/7/bits/stl_list.h:575:33:   required from ‘std::__cxx11::list<_Tp, _Alloc>::_Node* std::__cxx11::list<_Tp, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {opp::oscquery_server&, ofParameterGroup&}; _Tp = ofxOssiaNode; _Alloc = std::allocator<ofxOssiaNode>; std::__cxx11::list<_Tp, _Alloc>::_Node = std::_List_node<ofxOssiaNode>]’
/usr/include/c++/7/bits/stl_list.h:1801:32:   required from ‘void std::__cxx11::list<_Tp, _Alloc>::_M_insert(std::__cxx11::list<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {opp::oscquery_server&, ofParameterGroup&}; _Tp = ofxOssiaNode; _Alloc = std::allocator<ofxOssiaNode>; std::__cxx11::list<_Tp, _Alloc>::iterator = std::_List_iterator<ofxOssiaNode>]’
/usr/include/c++/7/bits/stl_list.h:1133:4:   required from ‘void std::__cxx11::list<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {opp::oscquery_server&, ofParameterGroup&}; _Tp = ofxOssiaNode; _Alloc = std::allocator<ofxOssiaNode>]’
/home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOscQueryServer.cpp:21:35:   required from here
/usr/include/c++/7/ext/new_allocator.h:136:4: error: no matching function for call to ‘ofxOssiaNode::ofxOssiaNode(opp::oscquery_server&, ofParameterGroup&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }

tested on Ubuntu 17.10, 
of commit 8e01052ec278bb52ecc26d511dd5da1c6f0ea31c
libossia on master branch with commit 46de6d1ad800d473b749fa29b52f89b42861e28d
on v3 branch with commit 7368eb0f1c290f72692060ad93bbf2dc460d477e

**Comment by bltzr** [comment]
> 
> first type of errors:
> In file included from /home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOssiaNode.h:4:0,
> from /home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOscQueryServer.h:9,
> from /home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOscQueryServer.cpp:9:
> /home/scrime/Documents/repos/openFrameworks/addons/ofxOscQuery/src/ofxOssiaTypes.h:213:22: error: ‘string’ does not name a type; did you mean ‘stdin’?
> using ofx_type = string;
> ^~~~~~
> stdin

could you try to replace with:
    using ofx_type = std::string;
    using ossia_type = std::string;
(adding std::) and tell me if that helps ?

**Comment by bltzr** [comment]
> On 20 Apr 2018, at 18:17, Thibaud Keller <notifications@github.com> wrote:
> 
> tested on Ubuntu 17.10,
> of commit 8e01052ec278bb52ecc26d511dd5da1c6f0ea31c
is that v0.10 ? because I only tested with 0.9.8 (with ofNode, BTW)

> libossia on master branch with commit 46de6d1ad800d473b749fa29b52f89b42861e28d
> on v3 branch with commit 7368eb0f1c290f72692060ad93bbf2dc460d477e
I haven’t tried with v3 yet, only with master
will have a try ASAP

**Comment by thibaudk** [comment]
I was using v0.10, Will retry all of this with 0.9.8.

ps : adding std:: didn't seem to have any effect on the error log.

**Comment by thibaudk** [comment]
after rebuilding with https://github.com/ofnode/of
and libossia's master branch
Only linkers errors remain
``FAILED: ../bin/ofxOSCquery-singleServer 
: && /usr/bin/c++  -O3 -march=native -std=c++98 -fdiagnostics-color -std=gnu++14 -O3 -DNDEBUG -g1 -Wno-psabi -fPIC  -lavahi-client -lavahi-common   -rdynamic CMakeFiles/ofxOSCquery-singleServer.dir/src/main.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/src/ofApp.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/src/CirclesRenderer.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxOscQuery/src/ofxOscQueryServer.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxBaseGui.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxButton.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxGuiGroup.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxLabel.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxPanel.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxSlider.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxSliderGroup.cpp.o CMakeFiles/ofxOSCquery-singleServer.dir/home/scrime/Documents/repos/of/addons/ofxGui/src/ofxToggle.cpp.o  -o ../bin/ofxOSCquery-singleServer  -Wl,-rpath,/home/scrime/Documents/repos/of/lib-linux/release-x86_64-64 -Wl,-rpath,'$ORIGIN' /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libPocoCrypto.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libPocoFoundation.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libPocoJSON.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libPocoNet.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libPocoNetSSL.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libPocoUtil.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libPocoXML.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libglfw.so /home/scrime/Documents/repos/of/lib-linux/release-x86_64-64/libopenFrameworks.so -lXi -lSM -lICE -lX11 -lXext -lXrandr -lXcursor -lXxf86vm -lXinerama -lz -lcairo -lGLU -lGL -lssl -lcrypto -lfreetype -lfontconfig -lfreetype -lboost_system -lboost_filesystem -lpthread -lasound -lopenal -lmpg123 -lsndfile -ludev -lglib-2.0 -lgthread-2.0 -lgmodule-2.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 /home/scrime/Documents/repos/of/addons/ofxOscQuery//libs/ossia/lib/linux64/libossia.a /home/scrime/Documents/repos/of/addons/ofxOscQuery//libs/ossia/lib/linux64/libServus.a -lavahi-client -lavahi-common -lcairo -lGLU -lGL -lssl -lcrypto -lfreetype -lfontconfig -lfreetype -lboost_system -lboost_filesystem -lpthread -lasound -lopenal -lmpg123 -lsndfile -ludev -lglib-2.0 -lgthread-2.0 -lgmodule-2.0 -lgstreamer-1.0 -lgstapp-1.0 -lgstbase-1.0 -lgstvideo-1.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 /home/scrime/Documents/repos/of/addons/ofxOscQuery//libs/ossia/lib/linux64/libossia.a /home/scrime/Documents/repos/of/addons/ofxOscQuery//libs/ossia/lib/linux64/libServus.a -lavahi-client -lavahi-common && :
/home/scrime/Documents/repos/of/addons/ofxOscQuery/src/ofxOscQueryServer.h:19 : erreur : référence à « opp::oscquery_server::oscquery_server() » non définie
``
The errors are repeated for ofxOssiaNode.h, ofxOssiaTypes.h many times over

**Comment by bltzr** [comment]
could you post the full log to a gist ?

maybe that’s because of the two slashes in /home/scrime/Documents/repos/of/addons/ofxOscQuery//libs/ossia/lib/linux64/libossia.a 
(before libs)
?

like, it seems not to find the libs, right ?

could you try to mess with the linux paths the addon_config.mk file to see if that helps ?

**Comment by bltzr** [comment]
@thibaudk : @avilleret just built on Linux using ofNode and it worked - could you give it a try ?

**Comment by thibaudk** [comment]
having trouble at moment building ofNode since the switch to ubuntu 18.04,
Will try again soon as I can.

**Comment by thibaudk** [comment]
Ok, so the problem was some broken dependencies on ubuntu with the ofnode install script. I finally got the example-singleserver working with ofxOscQery commit 7ed378094e0de80118f033d5354f8403141b77a0
and libossia commit c5ba78b061a1116b7ecdb0f2d3de560f2c4378ca
basicly, the setup before Sevrus became header only.

It woks great like that!

Building with latest commits tho returns the error 
src/ofxOscQueryServer.h:8:10: fatal error: ossia-cpp98.hpp: Aucun fichier ou dossier de ce type
 #include <ossia-cpp98.hpp>

Sorry I avn't been following closely, but where did the includes go?

**Comment by bltzr** [comment]
> 
> It woks great like that!
> 
> 
Fantastic!!!
> Building with latest commits tho returns the error
> src/ofxOscQueryServer.h:8:10: fatal error: ossia-cpp98.hpp: Aucun fichier ou dossier de ce type
> #include <ossia-cpp98.hpp>
> 
> Sorry I avn't been following closely, but where did the includes go?
> 
I suppressed them from the repo, the idea is to include the include + lib in the releases

I was waiting for the ossia release to do that : I was expecting it earlier, but there was some problem with the CI, apparently

So, you just have to build ossia with the CPP option, and move it to the right place

**Comment by thibaudk** [comment]
So I kept the include from the 7ed378094e0de80118f033d5354f8403141b77a0 commit and it compiles with libossia on latest commit c798f9b8fb3c4ef2f670b241f8aad275930e0ba0
well done! Thanks for the help!
