### ISSUE TITLE
can't compile in VS2017 OF master branch

### ISSUE THREAD

**Issue by moebiussurfing** [bltzr/ofxOscQuery#2]
hey, thanks for this addon. I just discovered this new protocol, and very curious  about Score too.

This are the error I am getting:

`Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "ossia-cpp98.hpp"	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	8	
Error (active)	E1696	cannot open source file "ossia-cpp98.hpp"	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	3	
Error (active)	E1696	cannot open source file "ossia-cpp98.hpp"	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaTypes.h	2	
Error (active)	E0757	overloaded function "std::chrono::duration<_Rep, _Period>::duration [with _Rep=long long, _Period=std::nano]" is not a type name	example-twoServers	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\chrono	195	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	44	
Error (active)	E0276	name followed by '::' must be a class or namespace name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	49	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	51	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	55	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	57	
Error (active)	E0276	name followed by '::' must be a class or namespace name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	62	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOscQueryServer.h	65	
Error (active)	E0276	name followed by '::' must be a class or namespace name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	647	
Error (active)	E0018	expected a ')'	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	647	
Error (active)	E0070	incomplete type is not allowed	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	647	
Error (active)	E0065	expected a ';'	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	647	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	695	
Error (active)	E0065	expected a ';'	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	700	
Error (active)	E0077	this declaration has no storage class or type specifier	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	708	
Error (active)	E0065	expected a ';'	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	708	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	711	
Error (active)	E0018	expected a ')'	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	727	
Error (active)	E0020	identifier "default" is undefined	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	727	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	728	
Error (active)	E0341	'operator=' must be a member function	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	728	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	728	
Error (active)	E1774	'= default' can only appear on default constructors, copy/move constructors, copy/move assignment operators, and destructors	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	728	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	729	
Error (active)	E0341	'operator=' must be a member function	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	729	
Error (active)	E0757	variable "ofxOssiaNode" is not a type name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	729	
Error (active)	E1774	'= default' can only appear on default constructors, copy/move constructors, copy/move assignment operators, and destructors	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	729	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	734	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	756	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	758	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	760	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	762	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	764	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	766	
Error (active)	E0276	name followed by '::' must be a class or namespace name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	774	
Error (active)	E0239	invalid specifier outside a class declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	775	
Error (active)	E0276	name followed by '::' must be a class or namespace name	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	783	
Error (active)	E0169	expected a declaration	example-twoServers	C:\Users\myUser\Documents\openframeworks\addons\ofxOscQuery\src\ofxOssiaNode.h	820	
Error	C1083	Cannot open include file: 'ossia-cpp98.hpp': No such file or directory (compiling source file src\ofApp.cpp)	example-twoServers	c:\users\myUser\documents\openframeworks\addons\ofxoscquery\src\ofxoscqueryserver.h	8	
Error	C1083	Cannot open include file: 'ossia-cpp98.hpp': No such file or directory (compiling source file src\main.cpp)	example-twoServers	c:\users\myUser\documents\openframeworks\addons\ofxoscquery\src\ofxoscqueryserver.h	8	
Warning	C4018	'<': signed/unsigned mismatch	example-twoServers	c:\users\myUser\documents\openframeworks\addons\ofxgui\src\ofxinputfield.cpp	276	
Error	C1083	Cannot open include file: 'ossia-cpp98.hpp': No such file or directory (compiling source file ..\..\..\addons\ofxOscQuery\src\ofxOscQueryServer.cpp)	example-twoServers	c:\users\myUser\documents\openframeworks\addons\ofxoscquery\src\ofxoscqueryserver.h	8	
`

**Comment by moebiussurfing** [comment]
btw, I saw your videos, and I want to ask you what's the better Windows alternative to the OSCQueryBrowser that you are using on MacOS.  Maybe should we use Vidvox/oscqueryhtml on windows?

**Comment by moebiussurfing** [comment]
PS: i don't see were is:

> A compiled version of libossia is included in the release.

**Comment by bltzr** [comment]
> btw, I saw your videos, and I want to ask you what's the better Windows alternative to the OSCQueryBrowser that you are using on MacOS. Maybe should we use Vidvox/oscqueryhtml on windows?
> 
> 
yes, that seems like the best option that I know of (I’m not very aware of anything Windows-related, unfortunately)

**Comment by bltzr** [comment]
> PS: i don't see were is:
> 
> > A compiled version of libossia is included in the release.

did you try to build from the repository or from [one of the releases](https://github.com/bltzr/ofxOscQuery/releases)  ?
because the compiled lib is not on the repository, only in the releases (to keep the repo's size small)

That's probably what's causing your problems above. Could you try and report back ?

Also, it's probably better to try with the example-singleServer

And, thanks for giving it a try!

**Comment by moebiussurfing** [comment]
ok, thanks. I tried with this release (https://github.com/bltzr/ofxOscQuery/releases/download/1.0/ofxOscQuery-v1.0.0.zip) and it compiled rigth. I created the project with Project Generator but I  had to drag ossia.lib and ossia_x64.lib manually, because they do not were into the generated project...

But when I play the Score extra demo project do not sync/makes nothing... Neither moving OF gui I see nothing linked..

On the ofxQueryDemo Score element settings I see: 
ws://bltzr.local.:4677 
I tried to change to localhost or Find Devices without success... I tried to change the port to 5678 too...

I will check more deeply some day. but I put this notes here because maybe it helps to clarify how to try it.

**Comment by moebiussurfing** [comment]
sorry for testing for this very "fast"... 
Now I see that the /openframeworks/addons/ofxOscQuery/example-singleServer/client.html example is working. When moving the html sliders, ofApp receives the parameters. not backwards from OF to web

**Comment by bltzr** [comment]
Thanks for testing @moebiussurfing !!!

Yes, the demo score is probably outdated, I should update it ASAP (no time for that today, sorry). 
Would you mind creating a separate issue for that, and also one for the data not coming back to the web client ?

Concerning the Project Generator, could you please describe in further detail where it was initiallly, after running the PG, and after moving it manually ?

Thanks !

**Comment by bltzr** [comment]
I finally found some time and just [committed](https://github.com/bltzr/ofxOscQuery/commit/d1c9721f7c2baf462efc6ab71f8449227cba0e48) fixes to the Demo score, would you mind testing that again, please ?

**Comment by moebiussurfing** [comment]
You are welcome

> Concerning the Project Generator, could you please describe in further detail where it was initiallly, after running the PG, and after moving it manually ?

I think that PG has not copied the lib anywhere. So I dragged to VS project folder and it worked.

I downloaded your new Demo.score, but stils not syncing.
The OF App logs this:
```
[warning] Could not set TCP nodelay option
servername: ofxOscQuery
[warning] Could not set TCP nodelay option
```

BTW I am not sure if I am testing it fine, because never used your Score software. What I do is to play the Score project and nothing happens to the OF App. Also tried to move OF gui sliders but nothing happens on left colum Score parameters inside myOfxOscQueryApplication folder...

Settings in Score are : ws://localhost.:5678, the same that the OF addon says is the defautl port...

**Comment by moebiussurfing** [comment]
> Concerning the Project Generator, could you please describe in further detail where it was initiallly, after running the PG, and after moving it manually ?

This is how PG makes the project structure:
![1](https://user-images.githubusercontent.com/2106149/46755305-18a0f900-cc9b-11e8-8a76-86cb25c55837.PNG)

And this is how I dragged the vs compiled content folder from /libs:
![2](https://user-images.githubusercontent.com/2106149/46755322-26ef1500-cc9b-11e8-93a1-f1bf657bc2a1.PNG)

This version of the addon is the release linked you sendme. The master branch addon with this lib files do not compiles.

I am running Realese/x64

**Comment by bltzr** [comment]
I'm not sure about the whole Project Generator thing (do you still have issues with that, BTW ?)

What I know, though is that this message:
```
[warning] Could not set TCP nodelay option
```
is perfectly harmless

**Comment by moebiussurfing** [comment]
now is working. thanks
